### ISSUE TITLE
Version on AnkiWeb not be updated(?) and has no 8bitdo micro support

### ISSUE THREAD

**Issue by ahdofm** [roxgib/anki-contanki#121]
The add on I downloaded from the AnkiWeb add on page doesn't have 8bitdo micro support, but I know that was added in one of the beta versions. 
So I tried downloading the add-on from github (I downloaded the "contanki" folder from v1.0/main contanki only; lmk if I should've downloaded it some other way) but am having trouble getting it to work properly and am getting the error message upon anki startup: 
"The following add-ons failed to load: ⁨contanki⁩
They may need to be updated to support this version of Anki. Click the Check for Updates button to see if any updates are available."

This is the debug info:
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-12.7.6-x86_64-i386-64bit

When loading contanki:
Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "/Users/emily/Library/Application Support/Anki2/addons21/contanki/__init__.py", line 8, in <module>
    from .contanki import Contanki
  File "/Users/emily/Library/Application Support/Anki2/addons21/contanki/contanki.py", line 14, in <module>
    from .quick import QuickSelectMenu
  File "/Users/emily/Library/Application Support/Anki2/addons21/contanki/quick.py", line 16, in <module>
    from .icons import get_button_icon
  File "/Users/emily/Library/Application Support/Anki2/addons21/contanki/icons.py", line 21, in <module>
    from .controller import Controller
  File "/Users/emily/Library/Application Support/Anki2/addons21/contanki/controller.py", line 8, in <module>
    import tomlkit
ModuleNotFoundError: No module named 'tomlkit'

Any help would be very much appreciated, as mapping the buttons wasn't as accurate with the other 8bitdo profile options!!!

[Screenshot 2024-09-19 at 11 45 01 ](https://github.com/user-attachments/assets/f1b205a6-12eb-47f6-a1dc-f71c7d87f262)

**Comment by ahdofm** [comment]
Nvm redownloaded from ankiweb again and now it shows the 8bitdo micro. Not sure why it wasn't before
