### ISSUE TITLE
Error Code on Controller's Auto Turn Off

### ISSUE THREAD

**Issue by yash-fn** [roxgib/anki-contanki#14]
The 8BitDo Zero 2 turns off after a certain delay for power saving. It can easily be turned on and connect back by clicking a button. However, every time the controller turns off like this, the entire add-on crashes with the following output:
*Also after it crashes entire anki must be reboot to regain functionality.

```python
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.10 Qt 6.3.1 PyQt 6.3.1
Platform: Linux
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-07-30 19:09:23
Add-ons possibly involved: ⁨Contanki - Controller Support for Anki beta⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 618, in _onBridgeCmd
  File "aqt.hooks_gen", line 4358, in __call__
  File "/home/USER/.local/share/Anki2/addons21/1898790263/contanki.py", line 109, in on_receive_message
    funcs[func](*args)
  File "/home/USER/.local/share/Anki2/addons21/1898790263/contanki.py", line 122, in poll
    mods = tuple(
  File "/home/USER/.local/share/Anki2/addons21/1898790263/contanki.py", line 123, in <genexpr>
    buttons[mod] if mod < 100 else (True if axes[mod - 100] else False)
IndexError: list index out of range
```

**Comment by roxgib** [comment]
Weird, seems to be polling after disconnecting. There are checks in the JS to prevent this but I've added similar checks to the Python code since it might be an async issue. You can try it with the latest commit or wait for the next beta which shouldn't be very long.

**Comment by roxgib** [comment]
I've just release Beta 7 to both GH and AnkiWeb - could you let me know if this issue is fixed?

**Comment by roxgib** [comment]
I'm going to close this but if it's not fixed be sure to let me know. Thanks again for reporting the problem.
