### ISSUE TITLE
DS4 Controller detection not working

### ISSUE THREAD

**Issue by itsanoel** [roxgib/anki-contanki#29]
DS4 controller controller detected as 8bit pro controller. Happens with DS4 windows and without. Emulating X360 controller with DS4 windows causes crash. Issues started after today's update.

Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-10-23 09:51:53

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 618, in _onBridgeCmd
  File "aqt.hooks_gen", line 4358, in __call__
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1898790263\contanki.py", line 117, in on_receive_message
    funcs[func](*args)
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1898790263\contanki.py", line 375, in register_controllers
    con = identify_controller(*(controller.split("%%%")))
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1898790263\controller.py", line 122, in identify_controller
    vendor_id, device_id = parse_controller_id(id_)
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\1898790263\controller.py", line 105, in parse_controller_id
    return (vendor_id.lower(), device_id.lower())
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by roxgib** [comment]
Thanks for reporting this. The crash has been addressed with [8902c91](https://github.com/roxgib/anki-contanki/commit/8902c91c60abf7eed356a7e1f20e39ac2bfbfc82).

The incorrectly identified controller is annoying. It happens because 8BitDo controllers masquerade as other controllers, so there's code to detect them, but apparently it's misidentifying the real thing. Would you be able to open the controller config, click help, and paste the debug info here? Might help with preventing this, otherwise 8BitDo owners will have to live with it.

**Comment by itsanoel** [comment]
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-10-23 09:51:53

1 controller detected:
Wireless Controller (STANDARD GAMEPAD Vendor: 054c Product: 05c4)
Buttons: 18
Axes: 4

Debug for DS4 controller detected as 8bitdo pro.

Thanks again for being so helpful and developing for this add-on.

**Comment by roxgib** [comment]
Thanks. This should be fixed in Beta 11 which I've just uploaded to AnkIWeb, please let me know if there are any other problems.
