### ISSUE TITLE
Addon error on Linux

### ISSUE THREAD

**Issue by mobedoor** [roxgib/anki-contanki#3]
Hello.
Clicking the config button throws an error. Debug info as follows 
```
Anki 2.1.50 (26d40c3a) Python 3.9.10 Qt 6.2.2 PyQt 6.2.2
Platform: Linux
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-04-13 04:55:55
Add-ons possibly involved: ⁨Contanki - Controller Support for Anki beta⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.addons", line 944, in onConfig
  File "/home/linuxuser/.local/share/Anki2/addons21/1898790263/contanki.py", line 147, in on_config
    ContankiConfig(mw, self.profile.copy())
AttributeError: 'NoneType' object has no attribute 'copy'
```
I removed all addons before testing to rule out conflicts.

**Comment by roxgib** [comment]
Thanks, fixed with f302952.
