### ISSUE TITLE
New Update Crashes Anki

### ISSUE THREAD

**Issue by Mudpile01** [roxgib/anki-contanki#31]
Hello,
The 10/24 update has caused anki to crash upon any button input. I could not get a crash report

**Comment by Mudpile01** [comment]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-10-24 11:10:55

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 618, in _onBridgeCmd
  File "aqt.hooks_gen", line 4358, in __call__
  File "C:\Users\shalabah\AppData\Roaming\Anki2\addons21\contanki\contanki.py", line 123, in on_receive_message
    funcs[func](*args)
  File "C:\Users\shalabah\AppData\Roaming\Anki2\addons21\contanki\contanki.py", line 329, in on_connect
    _controller = identify_controller(
  File "C:\Users\shalabah\AppData\Roaming\Anki2\addons21\contanki\controller.py", line 134, in identify_controller
    device_name = controller_ids["devices"][vendor_id][device_id]
KeyError: None

**Comment by roxgib** [comment]
Thanks, this should be fixed with [6c6bec3](https://github.com/roxgib/anki-contanki/commit/6c6bec31b5db361e1a955a97415999765c033f82) which is in the latest beta. Would you be able to confirm that it's fixed?

Also, assuming it's indeed fixed, it would be helpful if you could open up the controller options, click help, and paste the text that's there. This problem only affects certain controllers and I'm trying to collect some info on which ones are affected.

**Comment by roxgib** [comment]
Closing as it should now be fixed
