### ISSUE TITLE
Beta 11 still crashes

### ISSUE THREAD

**Issue by alexjonclement** [roxgib/anki-contanki#32]
Error
----
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Mac 13.0
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-10-25 09:09:03
Add-ons possibly involved: ⁨Contanki - Controller Support⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.addons", line 962, in onConfig
  File "/Users/*****/Library/Application Support/Anki2/addons21/contanki/contanki.py", line 104, in on_config
    ContankiConfig(focus, self.profile)
AttributeError: 'Contanki' object has no attribute 'profile'

**Comment by alexjonclement** [comment]
Error
———
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Mac 13.0
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-10-25 09:09:03
Add-ons possibly involved: ⁨contanki⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 618, in _onBridgeCmd
  File "aqt.hooks_gen", line 4358, in __call__
  File "/Users/*****/Library/Application Support/Anki2/addons21/contanki/contanki.py", line 123, in on_receive_message
  File "/Users/*****/Library/Application Support/Anki2/addons21/contanki/contanki.py", line 326, in on_connect
  File "/Users/*****/Library/Application Support/Anki2/addons21/contanki/contanki.py", line 372, in reset_controller
  File "/Users/*****/Library/Application Support/Anki2/addons21/contanki/contanki.py", line 87, in profile
  File "/Users/*****/Library/Application Support/Anki2/addons21/contanki/funcs.py", line 62, in get_config
  File "aqt.addons", line 703, in writeConfig
  File "aqt.addons", line 303, in writeAddonMeta
FileNotFoundError: [Errno 2] No such file or directory: '/Users/*****/Library/Application Support/Anki2/addons21/contanki/meta.json'

**Comment by roxgib** [comment]
Thanks for reporting, might be a Ventura issue as I haven't updated yet, Anki is supposed to handle meta.json itself. I'll investigate.

**Comment by roxgib** [comment]
I haven't been able to reproduce this. Can you try uninstalling and reinstalling the add-on?

**Comment by luke5595** [comment]
> I haven't been able to reproduce this. Can you try uninstalling and reinstalling the add-on?

I made an account just to give my input on this. I have fully uninstalled both Anki, and the add-on multiple times. I have the same error output. The add-on was working great on previous versions, until this update. Upon downgrading however, the prior addon versions no longer work.

**Comment by alexjonclement** [comment]
The latest (two?) updates seemed to fix it for me. I deleted the original add-on, then quit Anki. After re-installing the extension no longer crashes.

**Comment by luke5595** [comment]
> 

It is fixed as of the latest latest update! Not sure what changed, but this error is gone with the latest version
