### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by patience12g** [roxgib/anki-contanki#37]
When opening contanki add on config - this error message shows up. 
Ive tried updated my computer, and deleting and reinstalling the add in with no luck. 

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
Platform: Mac 13.0.1
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-11-13 17:15:22
Add-ons possibly involved: ⁨Contanki - Controller Support for Anki beta⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.addons", line 962, in onConfig
  File "/Users/patiencegarrett/Library/Application Support/Anki2/addons21/1898790263/contanki.py", line 105, in on_config
    ContankiConfig(focus, self.profile)
  File "/Users/patiencegarrett/Library/Application Support/Anki2/addons21/1898790263/config.py", line 100, in __init__
    self.options_page = OptionsPage(self)
  File "/Users/patiencegarrett/Library/Application Support/Anki2/addons21/1898790263/config.py", line 239, in __init__
    self.profile_bar = self.ProfileBar(parent)
  File "/Users/patiencegarrett/Library/Application Support/Anki2/addons21/1898790263/config.py", line 309, in __init__
    self.profile_combo.setCurrentIndex(p_list.index(self.profile.name))
ValueError: '8BitDo Zero' is not in list

**Comment by roxgib** [comment]
Thanks for reporting, this should be fixed with [70a0e99](https://github.com/roxgib/anki-contanki/commit/70a0e9964573487cda42615a246212e09a93d1ff) which will be in the next beta
