### ISSUE TITLE
Fails to load after latest update

### ISSUE THREAD

**Issue by jjp87** [roxgib/anki-contanki#42]
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Contanki - Controller Support for Anki beta⁩':
⁨Traceback (most recent call last):
  File "aqt\addons.py", line 230, in loadAddons
  File "C:\Users\james\AppData\Roaming\Anki2\addons21\1898790263\__init__.py", line 6, in <module>
    from .contanki import Contanki
  File "C:\Users\james\AppData\Roaming\Anki2\addons21\1898790263\contanki.py", line 13, in <module>
    from .quick import QuickSelectMenu
  File "C:\Users\james\AppData\Roaming\Anki2\addons21\1898790263\quick.py", line 17, in <module>
    from .actions import button_actions
  File "C:\Users\james\AppData\Roaming\Anki2\addons21\1898790263\actions.py", line 10, in <module>
    from aqt.utils import tooltip, is_mac
ImportError: cannot import name 'is_mac' from 'aqt.utils' (D:\Anki\aqt\utils.pyc)

Version ⁨2.1.49 (dc80804a)⁩
Python 3.8.6 Qt 5.14.2 PyQt 5.14.2

**Comment by roxgib** [comment]
Thanks, fixed with [57934a1](https://github.com/roxgib/anki-contanki/commit/57934a1c109eda2f9b923e391fe99eca3e8f507d). I do recommend updating to a more recent Anki version if possible.
