### ISSUE TITLE
Unable to Load on Mac

### ISSUE THREAD

**Issue by cmac3032** [roxgib/anki-contanki#45]
Getting the error message below. Tried uninstall/reinstall.

An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.  When loading '⁨Contanki - Controller Support for Anki beta⁩': ⁨Traceback (most recent call last):   File "aqt/addons.py", line 230, in loadAddons   File "/Users/Library/Application Support/Anki2/addons21/1898790263/__init__.py", line 6, in <module>     from .contanki import Contanki   File "/Users/Library/Application Support/Anki2/addons21/1898790263/contanki.py", line 13, in <module>     from .quick import QuickSelectMenu   File "/Users/Library/Application Support/Anki2/addons21/1898790263/quick.py", line 17, in <module>     from .actions import button_actions   File "/Users/Library/Application Support/Anki2/addons21/1898790263/actions.py", line 10, in <module>     from aqt.utils import tooltip, is_mac ImportError: cannot import name 'is_mac' from 'aqt.utils' (/Applications/Anki.app/Contents/MacOS/aqt/utils.pyc)

**Comment by cmac3032** [comment]
Downloaded latest version Anki and problem resolved.
