### ISSUE TITLE
Error after last Anki/Python Update

### ISSUE THREAD

**Issue by x51mon** [roxgib/anki-contanki#61]
I'm getting the following error after the last Anki update, though also Python got updated to 3.11 on my system, so that might be the reason for it.

Is there anything I need to change on my side because of the Python update?

```python
Anki 2.1.65 (141bc18b) Python 3.11.3 Qt 6.5.0 PyQt 6.5.0
Platform: Linux-5.15.114-2-MANJARO-x86_64-with-glibc2.37
Flags: frz=False ao=True sv=2
Add-ons, last update check: 2023-06-13 22:05:14
Möglicherweise beteiligte Erweiterungen: ⁨Contanki - Controller Support for Anki beta⁩

Caught exception:
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/aqt/webview.py", line 46, in cmd
    return json.dumps(self.onCmd(str))
                      ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aqt/webview.py", line 153, in _onCmd
    return self._onBridgeCmd(str)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/aqt/webview.py", line 656, in _onBridgeCmd
    handled, result = gui_hooks.webview_did_receive_js_message(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/_aqt/hooks.py", line 4384, in __call__
    handled = filter(handled, message, context)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simon/.local/share/Anki2/addons21/1898790263/contanki.py", line 124, in on_receive_message
    funcs[func](*args)
  File "/home/simon/.local/share/Anki2/addons21/1898790263/contanki.py", line 138, in if_connected_wrapper
    func(self, *args, **kwargs)
  File "/home/simon/.local/share/Anki2/addons21/1898790263/contanki.py", line 177, in poll
    self.do_action(state, i)
  File "/home/simon/.local/share/Anki2/addons21/1898790263/contanki.py", line 138, in if_connected_wrapper
    func(self, *args, **kwargs)
  File "/home/simon/.local/share/Anki2/addons21/1898790263/contanki.py", line 262, in do_action
    self.toggle_quick_select(state)
  File "/home/simon/.local/share/Anki2/addons21/1898790263/contanki.py", line 138, in if_connected_wrapper
    func(self, *args, **kwargs)
  File "/home/simon/.local/share/Anki2/addons21/1898790263/contanki.py", line 252, in toggle_quick_select
    self.show_quick_select(state)
  File "/home/simon/.local/share/Anki2/addons21/1898790263/contanki.py", line 138, in if_connected_wrapper
    func(self, *args, **kwargs)
  File "/home/simon/.local/share/Anki2/addons21/1898790263/contanki.py", line 226, in show_quick_select
    self.quick_select.appear(state)
  File "/home/simon/.local/share/Anki2/addons21/1898790263/quick.py", line 158, in appear
    for action, location in zip(self.buttons[state], self.get_geometry(state)):
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simon/.local/share/Anki2/addons21/1898790263/quick.py", line 147, in get_geometry
    return [
           ^
  File "/home/simon/.local/share/Anki2/addons21/1898790263/quick.py", line 148, in <listcomp>
    QPoint(*self.get_cart(angle, radius, x, y))
TypeError: arguments did not match any overloaded call:
  QPoint(): too many arguments
  QPoint(xpos: int, ypos: int): argument 1 has unexpected type 'float'
  QPoint(a0: QPoint): argument 1 has unexpected type 'float'

```

**Comment by x51mon** [comment]
Didn't pay attention to the error message, same as #53 and fixed with a388e4a.
