### ISSUE TITLE
Can't use D-pad on 8bitdo zero 2

### ISSUE THREAD

**Issue by AnKingMed** [roxgib/anki-contanki#77]
I get this error

> Error
> An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
> If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
> When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
> Debug info:
> Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
> Platform: macOS-14.2.1-x86_64-i386-64bit
> Flags: frz=True ao=True sv=3
> Add-ons, last update check: 2023-12-21 14:07:04
> Add-ons possibly involved: ⁨Contanki - Controller Support for Anki beta⁩
> 
> Caught exception:
> Traceback (most recent call last):
>   File "aqt.webview", line 50, in cmd
>   File "aqt.webview", line 157, in _onCmd
>   File "aqt.webview", line 680, in _onBridgeCmd
>   File "_aqt.hooks", line 5415, in __call__
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/1898790263/contanki.py", line 144, in on_receive_message
>     funcs[func](*args)
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/1898790263/contanki.py", line 163, in if_connected_wrapper
>     func(self, *args, **kwargs)
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/1898790263/contanki.py", line 228, in poll
>     self.do_axes_actions(state, axes)
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/1898790263/contanki.py", line 163, in if_connected_wrapper
>     func(self, *args, **kwargs)
>   File "/Users/Nick/Library/Application Support/Anki2/addons21/1898790263/contanki.py", line 339, in do_axes_actions
>     value = axes[axis]
> IndexError: list index out of range

Settings:
![image](https://github.com/roxgib/anki-contanki/assets/57678116/90964956-2002-4bb3-bf56-0a6344e196ea)

**Comment by AnKingMed** [comment]
Looks like connecting in D mode seems to resolve this issue
