### ISSUE TITLE
Error when remaping controller buttons

### ISSUE THREAD

**Issue by Vilhelm-Ian** [roxgib/anki-contanki#93]
Traceback (most recent call last):
  File "/home/jovan/.local/share/Anki2/addons21/1898790263/config.py", line 146, in save
    mw.contanki.profile = self._profile  # type: ignore
  File "/home/jovan/.local/share/Anki2/addons21/1898790263/contanki.py", line 116, in profile
    self.overlay = ControlsOverlay(mw, profile)
  File "/home/jovan/.local/share/Anki2/addons21/1898790263/overlay.py", line 72, in __init__
    for index, button in sorted(
  File "/home/jovan/.local/share/Anki2/addons21/1898790263/overlay.py", line 74, in <lambda>
    key=lambda inputs: BUTTON_ORDER.index(inputs[1]),
ValueError: '' is not in list

**Comment by roxgib** [comment]
Thanks for reporting, this should be fixed in the version release this morning
